1.关于数据集

In [1]:
from sklearn import datasets
iris=datasets.load_iris()
digits=datasets.load_digits()
print(digits.data)#获得数据
digits.target#获得数组型响应变量
digits.images[0]#对应着data中的数据，每一个元素都是8*8的二维数组，其元素代表的是灰度值。

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
C:\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

sklearn 有自带的数据集，类似与字典

In [2]:
import matplotlib.pyplot as plt
plt.figure(1,figsize=(3,3))
plt.imshow(digits.images[-1],cmap=plt.cm.gray_r,interpolation='nearest')
plt.show()

<Figure size 300x300 with 1 Axes>

In [3]:
digits.images.shape
data=digits.images.reshape((digits.images.shape[0],-1))#1797,64

当实例化估计器时，可以直接设置参数：estimator = Estimator(param1=1, param2=2)；

也可以以修改的方式进行：estimator.param1

当数据配有估计器时，参数将根据数据进行估计。 所有估计的参数都是估计对象的属性，以下划线结尾.
'estimator.estimated\_param\_'

2.关于估计器

In [5]:
from sklearn import svm
clf=svm.SVC(gamma=0.001,C=100.)#svm.SVM选择估计器
clf.fit(digits.data[:-1],digits.target[:-1])
clf.predict(digits.data[-1:])

array([8])

3.交叉验证通过score选择最优参数

给定一个估算器，交叉验证对象和输入数据集，cross_val_score将数据重复拆分为一个训练和一个测试集，使用该训练集训练该估算器，并根据测试集计算每次迭代的得分

4.模型拟合fit

每个估计器都要用到fit方法
feature即为column，fit(x,y)对于无监督学习，不需要指定y。

x和y一般为数组对象或类数组对象。

5.transformer object没有predict对象，但有transform方法，可以输出被转换的矩阵对象X.

transformer与estimator有相同的api

In [6]:
from sklearn.preprocessing import StandardScaler
x=[[0,15],[1,-10]]
x_t=StandardScaler().fit(x)
x_t.transform(x)

array([[-1.,  1.],
       [ 1., -1.]])

6.transformers+estimator/predictor=pipline

pipline与estimator有相同的api,有fit方法和predict方法

一般的管道( pipeline ) 包括了两个部分：
① 作为输入端的预处理器( pre-processor)：
转换(Transform)或者”推断？“( imputes )数据
② 作为输出端的预测器( predictor )：预测目标值的预测器( predictor )

In [7]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

In [8]:
pipe = make_pipeline(StandardScaler(),LogisticRegression(random_state=0))#创造一个pipeline对象(内有预处理和编辑器)

x,y=load_iris(return_X_y=True)
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)#下载数据并且分割训练集与测试集

pipe.fit(x_train,y_train)#fit the whole pipline
accuracy_score(pipe.predict(x_test),y_test)

C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.8157894736842105

7.model evaluation

模型训练完成之后应该立马进行模型评估，而不是直接去预测未见过的”新数据“。

除了train_test_split,scikit-learn提供了cross-validation方法切割样本 

In [ ]:
from skleran.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate
x,y=make_regression(n_samples=1000,random_state=0)
lr=LinearRegression()
result=cross_validate(lr,x,y)
result['test_score']

8.parameter searches
用RandomizedSearchCV选择最优参数

In [22]:
from sklearn.datasets import fetch_california_housing
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
from scipy.stats import randint

In [23]:
x,y=fetch_california_housing(return_X_y=True)
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)
# define the parameter space that will be searched over
param_distributions={'n_estimator':randint(1,5),'max_depth':randint(5,10)}
# create a searchCV object and fit it to the data
search=RandomizedSearchCV(estimator=RandomForestRegressor(random_state=0),n_iter=5,param_distributions=param_distributions,random_state=0)

In [19]:
search.fit(x_train,y_train)
# the search object now acts like a normal randomforest estimator
search.best_params_
search.score(x_test,y_test)

C:\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


ValueError: Invalid parameter n_estimator for estimator RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=9,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators='warn',
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False). Check the list of available parameters with `estimator.get_params().keys()`.